/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package root.main.swing;

import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import lombok.SneakyThrows;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.stereotype.Service;
import root.SpringJavaFxApplication;

import javax.swing.*;

/**
 * @author balin
 */
@Service
public class MainSwing extends javax.swing.JPanel {

    private final ConfigurableApplicationContext applicationContext;
    private final JFrame mainWindow;

    public MainSwing(ConfigurableApplicationContext applicationContext, SpringJavaFxApplication mainWindow) {
        this.applicationContext = applicationContext;
        this.mainWindow = mainWindow;
        initComponents();
        this.mainWindow.add(this);
        Platform.runLater(() -> {
            initFx(jFXPanel1);
        });
    }

    public void initFx(JFXPanel fxPanel) {
        applicationContext.getAutowireCapableBeanFactory().autowireBean(swingController1);
        Scene scene = createScene();
        fxPanel.setScene(scene);
    }

    @SneakyThrows
    public Scene createScene() {
        FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("/mainWindow.fxml"));
        fxmlLoader.setControllerFactory(applicationContext::getBean);

        Parent root = fxmlLoader.load();
        Scene scene = new Scene(root, 1200, 700);
        return scene;
        //scene.getStylesheets().add("/style.css");
//        scene.getStylesheets().add(BootstrapFX.bootstrapFXStylesheet());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFXPanel1 = new javafx.embed.swing.JFXPanel();
        swingController1 = new root.main.swing.SwingController();

        setLayout(new java.awt.BorderLayout());
        add(jFXPanel1, java.awt.BorderLayout.CENTER);
        add(swingController1, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javafx.embed.swing.JFXPanel jFXPanel1;
    private root.main.swing.SwingController swingController1;
    // End of variables declaration//GEN-END:variables
}
